version: '3'
services:
    webserver:
        container_name: webserver
        image: nginx:alpine
        ports:
            - ${WEBSERVER_PORT:-80}:80
        volumes:
            - ./api:/var/www
            - ./webserver/nginx.conf:/etc/nginx/nginx.conf
            - ./webserver/sites/:/etc/nginx/conf.d/
        networks:
            - frontend
            - backend
        depends_on:
          - app
          - api
          - phpmyadmin
    app:
        container_name: app
        build:
            context: ./app
            dockerfile: Dockerfile
        image: desafio-inpeace-app:latest
        networks:
          - backend
        environment:
          API_BASE_URL: http://api.localhost
    api:
        container_name: api
        build:
            context: ./api
            dockerfile: Dockerfile
            args:
                GID: ${GID:-1000}
        image: desafio-inpeace-api:latest
        networks:
          - backend
    mysql:
        container_name: mysql
        image: mysql:8.0
        networks:
            - backend
        volumes:
            - "mysqlvolume:/var/lib/mysql"
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_DATABASE: '${DB_DATABASE}'
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin:5.1
        networks:
          - backend
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        depends_on:
          - mysql

networks:
    frontend:
    backend:

volumes:
    mysqlvolume: